package com.twoheart.dailyhotel.model;

public class StayFilter
{
    public static final int MIN_PERSON = 2;
    public static final int MAX_PERSON = 10;

    public static final int FLAG_HOTEL_FILTER_BED_NONE = 0x00;
    public static final int FLAG_HOTEL_FILTER_BED_DOUBLE = 0x01;
    public static final int FLAG_HOTEL_FILTER_BED_TWIN = FLAG_HOTEL_FILTER_BED_DOUBLE << 1;
    public static final int FLAG_HOTEL_FILTER_BED_HEATEDFLOORS = FLAG_HOTEL_FILTER_BED_DOUBLE << 2;
    public static final int FLAG_HOTEL_FILTER_BED_CHECKIN = FLAG_HOTEL_FILTER_BED_DOUBLE << 3;
    //
    public static final int FLAG_HOTEL_FILTER_AMENITIES_NONE = 0x00;
    public static final int FLAG_HOTEL_FILTER_AMENITIES_PARKING = 0x01;
    public static final int FLAG_HOTEL_FILTER_AMENITIES_NO_PARKING = FLAG_HOTEL_FILTER_AMENITIES_PARKING << 1;
    public static final int FLAG_HOTEL_FILTER_AMENITIES_SHARED_BBQ = FLAG_HOTEL_FILTER_AMENITIES_PARKING << 2;
    public static final int FLAG_HOTEL_FILTER_AMENITIES_POOL = FLAG_HOTEL_FILTER_AMENITIES_PARKING << 3;
    public static final int FLAG_HOTEL_FILTER_AMENITIES_BUSINESS_CENTER = FLAG_HOTEL_FILTER_AMENITIES_PARKING << 4;
    public static final int FLAG_HOTEL_FILTER_AMENITIES_FITNESS = FLAG_HOTEL_FILTER_AMENITIES_PARKING << 5;
    public static final int FLAG_HOTEL_FILTER_AMENITIES_SAUNA = FLAG_HOTEL_FILTER_AMENITIES_PARKING << 6;
    public static final int FLAG_HOTEL_FILTER_AMENITIES_PET = FLAG_HOTEL_FILTER_AMENITIES_PARKING << 7;
    public static final int FLAG_HOTEL_FILTER_AMENITIES_KIDS_PLAY_ROOM = FLAG_HOTEL_FILTER_AMENITIES_PARKING << 8;
    //
    public static final int FLAG_HOTEL_FILTER_ROOM_AMENITIES_NONE = 0x00;
    public static final int FLAG_HOTEL_FILTER_ROOM_AMENITIES_WIFI = 0x01;
    public static final int FLAG_HOTEL_FILTER_ROOM_AMENITIES_COOKING = FLAG_HOTEL_FILTER_ROOM_AMENITIES_WIFI << 1;
    public static final int FLAG_HOTEL_FILTER_ROOM_AMENITIES_PC = FLAG_HOTEL_FILTER_ROOM_AMENITIES_WIFI << 2;
    public static final int FLAG_HOTEL_FILTER_ROOM_AMENITIES_BATHTUB = FLAG_HOTEL_FILTER_ROOM_AMENITIES_WIFI << 3;
    public static final int FLAG_HOTEL_FILTER_ROOM_AMENITIES_TV = FLAG_HOTEL_FILTER_ROOM_AMENITIES_WIFI << 4;
    public static final int FLAG_HOTEL_FILTER_ROOM_AMENITIES_SPA_WHIRLPOOL = FLAG_HOTEL_FILTER_ROOM_AMENITIES_WIFI << 5;
    public static final int FLAG_HOTEL_FILTER_ROOM_AMENITIES_PRIVATE_BBQ = FLAG_HOTEL_FILTER_ROOM_AMENITIES_WIFI << 6;
    public static final int FLAG_HOTEL_FILTER_ROOM_AMENITIES_BREAKFAST = FLAG_HOTEL_FILTER_ROOM_AMENITIES_WIFI << 7;
    public static final int FLAG_HOTEL_FILTER_ROOM_AMENITIES_KARAOKE = FLAG_HOTEL_FILTER_ROOM_AMENITIES_WIFI << 8;
    public static final int FLAG_HOTEL_FILTER_ROOM_AMENITIES_PARTY_ROOM = FLAG_HOTEL_FILTER_ROOM_AMENITIES_WIFI << 9;
}
